"""Explicit portable register construction, never called by read-only verifier."""
import argparse,json,hashlib,zipfile
from pathlib import Path

def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(root,name,value):(root/name).write_bytes((json.dumps(value,ensure_ascii=False,sort_keys=True,indent=2,allow_nan=False)+'\n').encode('utf-8'))
def main(root):
    root=root.resolve();refs=root/'references'
    with zipfile.ZipFile(refs/'MRAB_R1_Engineering_Design_Package_0.1.zip') as z:old=json.loads(z.read('mrab_r1_engineering_design_0.1/MRAB_R1_SOURCE_REGISTER.json'))
    entries=[];oldby={Path(r['path']).name:r for r in old['sources']}
    for i,p in enumerate(sorted((refs/'sources').glob('*'))):
        prior=oldby.get(p.name);entries.append(dict(id=prior['id'] if prior else 'AUX:'+str(i),path=p.relative_to(root).as_posix(),sha256=sha(p),
            role=prior['role'] if prior else 'Task or additional read-only reference; not interchangeable with architectural canon',
            original_register_sha256=prior['sha256'] if prior else None,original_hash_matches=sha(p)==prior['sha256'] if prior else None,
            used_sections=prior['used_sections'] if prior else ['Read as named by Design Closure task']))
    for p in sorted(refs.iterdir()):
        if p.is_file():entries.append(dict(id='INPUT:'+p.stem,path=p.relative_to(root).as_posix(),sha256=sha(p),role='Preserved task/audit/authority/reproduction input'))
    request=refs/'ORIGINAL_PASTED_REQUEST.txt'
    write(root,'MRAB_R1_SOURCE_REGISTER.json',dict(artifact='MRAB_R1_SOURCE_REGISTER_0.2.1',sources=entries,
        original_request_hash=old['request_attachment_sha256'],actual_request_hash=sha(request),original_request_matches=sha(request)==old['request_attachment_sha256'],
        canonical_documents_modified=False,removed_source=dict(name='98_ВАЛИДАЦИЯ_И_ДОСТОВЕРНОСТЬ',status='NOT_REQUIRED',authority='references/AUTHOR_DECISION_98.md',original_message_export_sha256=None),
        unavailable_supplemental=['MRAB_R1_Hard_Audit_0.1.md','MRAB_R1_Audit_Evidence.zip'],unavailable_scope='Not found in supplied workspace and named Desktop transmission materials; not a whole-computer search',
        external_technical_references=old['external_technical_references']))
    metrics=[]
    def m(id,unit,scope,window,num,den,formula,inputs,exclusions,missing,comparator,checks='SPECIFIED_ONLY'):
        metrics.append(dict(id=id,unit=unit,scope=scope,window=window,numerator=num,denominator=den,formula=formula,input_pointers=inputs,
            exclusions=exclusions,missingness=missing,comparator=comparator,reason_codes=missing.split('|'),verification=checks))
    ep='schemas/r1_episode_record.schema.json#';prof='schemas/r1_self_profile.schema.json#';traj='schemas/r1_trajectory.schema.json#'
    w='E02 fixed: pilot MAIN target13..24; smoke MAIN target5..8; TRANSFER separately. Per trajectory first, then unweighted paired trajectory summaries.'
    absent='NO_ELIGIBLE_EPISODES|INFRA_INVALID|NOT_APPLICABLE_CONDITION'
    for id,num,scope,win in [
        ('OPERATIONAL_POST_MISMATCH_AUTONOMOUS_ERROR_RATE','count chosen_action=SOLO and solo_correct=false','C3 MAIN target downward mass>.90, n>=4 before ACTION by exact operational key','Eligible MAIN target episodes; no transfer'),
        ('OPERATIONAL_POST_SUPPORT_TOOL_RATE','count chosen_action in VERIFY,DELEGATE','C2 MAIN target upward mass>.90 AND Pr(p>.8)>.90, n>=4 before ACTION by exact key','Eligible MAIN target episodes; no transfer'),
        ('FIXED_AUTONOMOUS_ERROR_RATE','count chosen_action=SOLO and solo_correct=false','All B0-B4 C0-C3 target/control separately',w),
        ('FIXED_TOOL_RATE','count chosen_action in VERIFY,DELEGATE','All B0-B4 target/control',w),
        ('TARGET_ACCURACY','count final_correct=true and protocol_status=OK','All architectures target/control separately',w),
        ('COMPLETION_RATE','count feedback.outcome in CORRECT,INCORRECT','All architectures',w),
        ('ABSTAIN_RATE','count feedback.outcome=ABSTAINED','All architectures',w),
        ('PROTOCOL_FAILURE_RATE','count protocol_status=PROTOCOL_FAILURE','All architectures',w)]:
        m(id,'trajectory rate [0,1]',scope,win,num,'count eligible opportunities incl other actions, abstain and protocol failures',num+' / denominator',
            [ep+'/properties/feedback',ep+'/properties/execution_context',ep+'/properties/evaluator_private'],['Ordinary non-PREP INFRA_FAILURE attrition reported; R1-PREP-01 abnormal skipped PREP remains ITT with failure outcomes, not normal evidence/savings'],absent,'B3-B1/B2/B4; C1 B3-B0/B2','METRIC:four-outcomes; PREP21:abnormal-remains-ITT; BETA:mismatch-not-solo; E07:*; full data aggregation SPECIFIED_ONLY')
    m('CONDITIONAL_SOLO_ERROR','rate','Same C3 scope as primary','Post directional E before action','SOLO incorrect','SOLO opportunities','incorrect SOLO / SOLO count',[ep+'/properties/feedback'],['Non-SOLO'],absent,'B3-B1/B2/B4','METRIC:four-outcomes arithmetic; runtime SPECIFIED_ONLY')
    m('REFERENCE_POLICY_TOOL_RATE','rate','C2 reference_mean>=tau and directional E; policy-relative only',w,'VERIFY/DELEGATE','eligible opportunities','tools / eligible',[traj+'/properties/calibration_cells',ep+'/properties/feedback'],['Not primary operational irrationality measure'],absent,'B3-B1/B2/B4')
    m('ACCURATE_REFERENCE_PROFILE_CONDITION_EFFECT','vector of paired differences','C1 target and control separately','MAIN; E07 guard','B3 accuracy loss and resource ratios relative comparator','Same eligible paired trajectories; resources denominator comparator','accuracy_loss=accuracy_X-accuracy_B3; resource=B3/X-1, each resource separately',[ep+'/properties/feedback',ep+'/properties/calls',ep+'/properties/tool_event'],['Infra paired attrition; unknown usage not zero'],'MISSING_RESOURCE|DIVISION_BY_ZERO|LOW_PAIRED_N','B0 and B2 guards','E07:C1-HARM-EQUAL-COST')
    m('REFERENCE_PROFILE_DISTANCE','mean absolute probability midpoint distance','Numeric applicable claims in B0-B3 C1-C3','Each pre-ACTION snapshot, target/control separately','sum abs((lower+upper)/2 - reference posterior mean)','count numeric applicable claims with exact available calibration cell','sum distance / numeric count; no inference of operational truth or interval quality',[prof+'/$defs/claim',traj+'/properties/calibration_cells'],['UNKNOWN; narrower scope without reference cell'],'NO_NUMERIC_APPLICABLE_CLAIMS|NOT_APPLICABLE_NO_PROFILE|CALIBRATION_SCOPE_NOT_AVAILABLE','Within profile and descriptive B3-B2; B4 N/A','CAPABILITY:reference-live-counterexample; METRIC:ALL_UNKNOWN')
    m('MAP_AVAILABILITY','rate','Existing applicable slots; C0/B4 N/A','Each pre-ACTION snapshot','count non-UNKNOWN applicable claims','count applicable slots','numeric available / applicable slots',[prof+'/$defs/claim'],['Not a maturity or correctness score'],'NO_APPLICABLE_SCOPE|NOT_APPLICABLE_NO_PROFILE','B3-B0/B2','METRIC:ALL_UNKNOWN')
    m('REFERENCE_DISTANCE_WORSENING_RATE','rate','Accepted numeric updates, exact reference cell before/after','Entire trajectory; target/control separately','count numeric updates Pr_cal(dnew-dold>delta)>.90','count determinate WORSENED/IMPROVED/UNCHANGED numeric updates','Integrate Beta calibration density over event regions; WORSENED if above; IMPROVED if Pr(dold-dnew>delta)>.90; UNCHANGED if Pr(abs(dnew-dold)<=delta)>.90; else INDETERMINATE. Rate=WORSENED/determinate.',[prof+'/$defs/update_event',traj+'/properties/calibration_cells'],['Rejected, nonnumeric, changed scope without exact cell, indeterminate'],'NO_DETERMINATE_NUMERIC_UPDATES|CALIBRATION_SCOPE_NOT_AVAILABLE|NOT_APPLICABLE_NO_PROFILE','B3-B2','SPECIFIED_ONLY integration; no true live error inferred')
    m('FALSE_REVISION_RATE','not identified','Operational truth','All','Not identifiable from reference','Not applicable','Always value=null; reference distance cannot identify current operational truth',[prof+'/$defs/update_event'],['Deprecated universal truth interpretation'],'OPERATIONAL_TRUTH_NOT_IDENTIFIED','None','METRIC:OPERATIONAL_TRUTH')
    m('CONTROL_CLAIMS_TOUCHED_PROPORTION','rate [0,1]','Existing control slots B0-B3 C1-C3','Whole trajectory','count distinct control claim IDs with COMMITTED event','count eligible control claim IDs','distinct IDs / eligible IDs',[prof+'/$defs/update_event',ep+'/properties/evaluator_private'],['Rejected; C0/B4 N/A'],'NOT_APPLICABLE_NO_PROFILE|NO_ELIGIBLE_CLAIMS','B3-B2/B0','METRIC:control-repeat')
    m('CONTROL_UPDATE_EVENTS_PER_CLAIM','count per claim, may exceed1','Control slots','Whole trajectory','count committed proposals, not intermediate status stages','count eligible control claim IDs','events / claim IDs',[prof+'/$defs/update_event'],['Rejected; internal QUESTIONED stage not second proposal'],'NOT_APPLICABLE_NO_PROFILE|NO_ELIGIBLE_CLAIMS','B3-B2','METRIC:control-repeat')
    m('CONTROL_BEHAVIORAL_DAMAGE','vector','Control family','MAIN and transfer separately','B3-control accuracy loss; resource excess','Paired trajectory data','Same formulas and C1 guards as condition effect; touched count is not damage',[ep+'/properties/feedback',ep+'/properties/calls'],['No damage inference from text update alone'],'MISSING_CI|LOW_PAIRED_N|MISSING_RESOURCE','B3-B0/B2','E07:C1-HARM-EQUAL-COST')
    m('SCOPE_ERROR_RATE','rate','All submitted B2/B3 proposals','Whole trajectory','count attempts with SCOPE_VIOLATION or NO_LOCAL_EVIDENCE','count submitted proposals incl rejected','violations / attempts; multiple codes count once',[prof+'/$defs/update_event/properties/rejection_codes'],['No proposal; permitted exact restore not error'],'NO_SUBMITTED_PROPOSALS|NOT_APPLICABLE_READONLY','B3-B2','COMMIT:reject-foreign-family; COMMIT:no-configuration-relabel')
    m('EVIDENCE_RESPONSE_LATENCY','target opportunities with censor/early flags','First directional E for target operational key','First E before ACTION through final MAIN target opportunity','Response ordinal minus E ordinal','Not a ratio','max(0,response-E); early if response<E; no response right-censor at last-E; no E NOT_AT_RISK. Applicable response QUESTIONED/UNKNOWN/REVISED/NARROWED or ACTIVE with local refs.',[prof+'/$defs/update_event',ep+'/properties/execution_context'],['Transfer not silently included'],'NOT_AT_RISK|RIGHT_CENSORED|NOT_APPLICABLE_NO_PROFILE','B3-B2; association not causal','METRIC:early-censor-grace')
    m('UNADDRESSED_MISMATCH_RATE','rate','Target mismatch-key opportunities B0-B3','First directional E through MAIN, omit first2 target opportunities from that E','count opportunities without applicable addressed response','available post-grace opportunities','unaddressed / available; UNKNOWN limits map rights but does not prove accuracy',[prof+'/$defs/update_event',ep+'/properties/evaluator_private'],['Grace2; nonmatching key; transfer'],'NO_POST_GRACE_OPPORTUNITIES|NOT_AT_RISK|NOT_APPLICABLE_NO_PROFILE','B3-B2/B0','METRIC:early-censor-grace; full response matching SPECIFIED_ONLY')
    m('BEHAVIORAL_UPDATE_ASSOCIATION','action/accuracy difference vector','First addressed response, same applicable target key','up to4 before and4 after, minimum2 each','post action proportion minus pre action proportion; same accuracy/error calculation','Each side own eligible opportunities','Vector post-pre for SOLO/VERIFY/DELEGATE/ABSTAIN/errors/accuracy; failures retained; no cause inference',[prof+'/$defs/update_event',ep+'/properties/feedback'],['No response; too short sides'],'SHORT_WINDOW|NO_ADDRESSED_RESPONSE|NOT_APPLICABLE_NO_PROFILE','Within trajectory; summary B3-B2','SPECIFIED_ONLY full window aggregation')
    for id,num,den,window in [
        ('DECLARED_PROBE_COUNT','count DECLARED unique probe_id','Not a ratio','All episodes'),
        ('EXECUTED_DECLARED_PROBE_COUNT','count distinct declared probe_id with executed=true ACTION event','Not a ratio','All episodes'),
        ('PROBE_COUNT','count informative VERIFY observations (includes non-declared)','Not a ratio','All episodes'),
        ('RESTART_COUNT','count latch true->false caused by allowed public trigger','Not a ratio','All episodes'),
        ('STOP_UNFINISHED_RATE','count B3 PREP outputs with stop_reflection=false','count valid B3 PREP outputs','All episodes'),
        ('REFERENCE_POLICY_PROBE_RATE','count VERIFY with ref_mean>=tau and post directional E','count VERIFY','MAIN target only')]:
        m(id,'count' if den=='Not a ratio' else 'rate','B3 declared/controller metrics; PROBE_COUNT all arms',window,num,den,num if den=='Not a ratio' else num+' / '+den,[ep+'/properties/probe_events',ep+'/properties/latch_events',ep+'/properties/prep_record',ep+'/properties/feedback'],['Do not count cancelled/pending as executed; no discrimination score'],'NO_ELIGIBLE_EPISODES|NOT_APPLICABLE_ARCHITECTURE','B3 description; all-arm informative VERIFY comparison','TRACE:*; count aggregation SPECIFIED_ONLY')
    m('TRANSFER_RETENTION','vector','Same family/scope applicability; surface-only transfer','Pilot transfer25..32 minus MAIN13..24; smoke transfer9..12 minus MAIN5..8','differences accuracy/autonomous-error/tools plus applicability coverage','Own window opportunities','transfer rate minus late-MAIN rate; report both denominators',[ep+'/properties/feedback',ep+'/properties/evaluator_private',prof+'/$defs/claim'],['No inferential general skill claim'],'NO_ELIGIBLE_EPISODES|NO_APPLICABLE_SCOPE','B3-B1/B2/B4')
    for id,formula in [('EXACT_MODEL_TOKENS','sum input+output if output includes reasoning; else input+output+reasoning. Only OBSERVED and known accounting. Cached subset not added.'),('REFLECTION_TOKENS','sum observed input+output for PREP and REPAIR(repair_of=PREP) once'),('TOOL_UNITS','sum tool_event.cost_units'),('LATENCY_MS','sum nonoverlapping recorded model/tool durations, no replay inference'),('MONETARY_COST','sum observed/estimated call/tool cost at pinned currency and rate source; separate availability; unknown component -> null')]:
        m(id,'tokens/units/ms/currency as named','Whole trajectory, phase subtotals','All accepted attempts incl timeout',formula,'Not a ratio',formula,[ep+'/$defs/call_usage',ep+'/$defs/tool_event'],['No hidden reasoning text; reported reasoning count only'],'MISSING_RESOURCE|UNKNOWN_ACCOUNTING|UNSPECIFIED_CURRENCY','B3/X-1 per resource; division0 -> null','USAGE:* except actual monetary price aggregation SPECIFIED_ONLY')
    for id,formula,missing in [
        ('EVIDENCE_REACH','number trajectories with eligible conditional window / planned and valid trajectories separately','NO_VALID_TRAJECTORIES'),
        ('DENOMINATOR_DISTRIBUTION','sorted per-trajectory eligible counts, zeros retained; min, median, max from list','NO_VALID_TRAJECTORIES'),
        ('INFRA_ATTRITION','planned trajectories - valid trajectories, with mutually exclusive first non-PREP infra reason; paired blocks excluded together except author-prescribed abnormal PREP nonexecution retained in ITT','NONE'),
        ('PAIRED_N','count matched valid block_id intersection B3 and comparator for condition/stratum/target family','LOW_PAIRED_N'),
        ('RESOURCE_COMPARABILITY','all preregistered observed resource-ratio CIs entirely within ±.20; unknown reasoning prevents exact total compute claim','MISSING_RESOURCE|DIVISION_BY_ZERO|UNKNOWN_ACCOUNTING'),
        ('DIFFERENTIAL_REACH','abs(reach_B3-reach_X)<=.25 and min reach>=.50','LOW_OR_DIFFERENTIAL_REACH'),
        ('OUTCOME_CLASS','E07 ordered findings: mixed, harm, redundant OR B2/B4 using EQUIVALENT AND (fixed structurally more complex OR materially more expensive); RESOURCE_ADVANTAGE_B3 preserved independently; B1 explanation, promising all guards, else insufficient','CI_OR_GUARD_UNRESOLVED|MISSING_CI|UNKNOWN_USAGE|LOW_PAIRED_N|LOW_OR_DIFFERENTIAL_REACH')]:
        m(id,'diagnostic/gate, not model score','Condition and named comparator','E02/E03 prespecified windows','As explicit formula','As explicit formula',formula,[traj+'/properties/block_id',ep+'/properties/feedback',ep+'/properties/execution_context'],['Episode pooled inference prohibited'],missing,'B3-B1/B2/B4','E07:*; full bootstrap SPECIFIED_ONLY')
    write(root,'MRAB_R1_METRIC_REGISTER_0.2.1.json',dict(artifact='MRAB_R1_METRIC_REGISTER_0.2.1',metrics=metrics,
        serialization_contract=dict(rate=['value:number|null','numerator:integer>=0','denominator:integer>=0','excluded_count:integer>=0','excluded_by_reason:map code->integer','missing_reason:string|null'],
            vector='map named metric component -> same typed scalar/rate record; no sum across components',count='value integer>=0, eligible_scope, missing_reason; count0 is allowed when applicable',
            latency='value:integer>=0|null, early:boolean, censored:boolean, reason:string|null, post_grace_denominator:integer>=0',
            trajectory_report='trajectory_id, condition/architecture private, metrics map with registered IDs, exclusions and reasons; no unspecified scalar score',
            aggregate='condition,stratum,target_family,comparator,metric_id,paired_n,unmatched_n,reach[2],denominator_distribution[2],point,CI[lower,upper] or null,missing_reason,usage provenance',
            classifier_input='c1:target_accuracy_loss/control_accuracy_loss CI and resource_ratios map; comparators B1/B2/B4 each usage_known bool, resource_ratios map, C2/C3 {n_pairs int,primary_ci,fixed_ci,accuracy_loss,completion_loss CI, reach[2],point}; CIs finite ordered numeric pairs. Missing -> uncertainty; invalid input rejected.',
            classifier_output='decision_status CLASSIFIABLE/INSUFFICIENT_EVIDENCE; outcome_class enum E07 or null; comparator_findings array(comparator,kind,reason); uncertainty_reasons array; unit TRAJECTORY; result_kind'),
        deprecated_aliases={'Calibration MAE':'REFERENCE_PROFILE_DISTANCE','FALSE_REVISION_RATE':'null OPERATIONAL_TRUTH_NOT_IDENTIFIED','FALSE_LOW_EXCESS_TOOL_USE':'replaced by operational primary; old reference formula REFERENCE_POLICY_TOOL_RATE','CORRECTION_LATENCY':'EVIDENCE_RESPONSE_LATENCY, changed meaning','MISSED_REVISION_RATE':'UNADDRESSED_MISMATCH_RATE, changed meaning','BEHAVIORAL_UPDATE_EFFECT':'BEHAVIORAL_UPDATE_ASSOCIATION, no causal assertion','UNNECESSARY_PROBE_RATE':'REFERENCE_POLICY_PROBE_RATE'},
        patch021_decisions=dict(probe_scope='R1-PROBE-01 BOUNDED_EVIDENCE_PROBE; no causal discrimination entitlement from labels',
            redundancy='R1-REDUNDANCY-01; predeclared relation, no new complexity metric',
            prep='R1-PREP-01; abnormal nonexecution retained ITT; comparator.normal_execution_comparison=false if either-arm contrast relies on abnormal PREP skips: no costlier/comparable/cheaper architecture claim; resource_advantage_eligible=false separately where claimed advantage relies on nonexecution. Defaults true only for all-normal synthetic summaries, future values derived from logs, never agent assertions. No new endpoint',
            b4='R1-B4-01; strong0.2 policy retained'),
        empirical_runs=0))
    print(json.dumps(dict(source_entries=len(entries),metrics=len(metrics),canonical_hashes_match=all(e['original_hash_matches'] for e in entries if e.get('original_register_sha256')),request_hash_matches=sha(request)==old['request_attachment_sha256'])))

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--package',type=Path,required=True);main(p.parse_args().package)
